spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  # redis:
  #   host: redis
  #   port: 6379

  data:
    mongodb:
      uri: mongodb+srv://adminColdplay:A0Qmud4BgwVmOsaF@cluster0.w5qkm.mongodb.net/authDB?appName=Cluster0

  mail:
    host: smtp.gmail.com
    port: 587
    username: abhishekwanve369@gmail.com
    password: hbsbmnvmkswjztbq  # Use App Password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8083

eureka:
  instance:
    hostname: notification-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://service-registry:8761/eureka
