spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: http://localhost:9092

  # redis:
  #   host: redis
  #   port: 6379

  data:
    mongodb:
      uri: mongodb+srv://adminColdplay:A0Qmud4BgwVmOsaF@cluster0.w5qkm.mongodb.net/authDB?retryWrites=true&w=majority&appName=Cluster0

  mail:
    host: smtp.gmail.com
    port: 587
    username: abhishekwanve369@gmail.com
    password: hbsbmnvmkswjztbq  # Use App Password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8083

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
