server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: localhost

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service-updated
          uri: http://localhost:7777
          predicates:
            - Path=/authgateway/**
          filters:
            - StripPrefix=1

        - id: ticket-service
          uri: http://localhost:8089
          predicates:
            - Path=/ticketgateway/**
          filters:
            - StripPrefix=1

        - id: ticket-processing-service
          uri: http://localhost:8082
          predicates:
            - Path=/ticketprocessing/**
          filters:
            - StripPrefix=1

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

  main:
    web-application-type: reactive
