apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
  namespace: coldplay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
        - name: service-registry
          image: 18219526/coldplay-service-registry:1.0
          ports:
            - containerPort: 8761
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8761
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: service-registry
  namespace: coldplay
spec:
  selector:
    app: service-registry
  ports:
    - port: 8761
      targetPort: 8761
  type: ClusterIP
