kubectl apply -f k8s/namespace.yml
kubectl apply -f k8s/zookeeper/deployment.yml
kubectl apply -f k8s/kafka/deployment.yml
kubectl apply -f k8s/service-registry/deployment.yml
kubectl apply -f k8s/auth-service/deployment.yml
kubectl apply -f k8s/ticket-service/deployment.yml
kubectl apply -f k8s/ticket-processing/deployment.yml
kubectl apply -f k8s/notification-service/deployment.yml
kubectl apply -f k8s/api-gateway/deployment.yml
kubectl apply -f k8s/frontend/deployment.yml
